### ISSUE TITLE
Does not work? (cannot find tree-sitter)

### ISSUE THREAD

**Issue by jonsmithers** [cucumber/language-server#56]
### 👓 What did you see?

```console
➜  ~ # npm install --global @cucumber/language-server

added 112 packages, and audited 113 packages in 14s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  ~ # cucumber-language-server --version
Error: Cannot find module 'tree-sitter'
Require stack:
- /usr/local/lib/node_modules/@cucumber/language-server/node_modules/@cucumber/language-service/dist/cjs/src/tree-sitter-node/NodeParserAdapter.js
- /usr/local/lib/node_modules/@cucumber/language-server/dist/cjs/src/node/startNodeServer.js
- /usr/local/lib/node_modules/@cucumber/language-server/bin/cucumber-language-server.cjs
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Function.Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@cucumber/language-server/node_modules/@cucumber/language-service/src/tree-sitter-node/NodeParserAdapter.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

### ✅ What did you expect to see?

The executable installed by this module should not crash.

### 📦 Which tool/library version are you using?

0.12.10

### 🔬 How could we reproduce it?

```console
➜  ~ # npm install --global @cucumber/language-server
➜  ~ # cucumber-language-server --version
```

### 📚 Any additional context?

I'm trying to use this lsp with neovim via [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#cucumber_language_server).

**Comment by aurelien-reeves** [comment]
Hi,

Thanks for your report

Do you have the possibility to test a local install rather than a global one? To check if the global install is responsible for the issue or not

**Comment by jonsmithers** [comment]
It does reproduce locally:

```console
➜  test-dir # npm add @cucumber/language-server
...
➜  test-dir # node_modules/.bin/cucumber-language-server --version
Error: Cannot find module 'tree-sitter'
Require stack:
- /Users/jsmithers/deleteme/node_modules/@cucumber/language-service/dist/cjs/src/tree-sitter-node/NodeParserAdapter.js
- /Users/jsmithers/deleteme/node_modules/@cucumber/language-server/dist/cjs/src/node/startNodeServer.js
- /Users/jsmithers/deleteme/node_modules/@cucumber/language-server/bin/cucumber-language-server.cjs
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Function.Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/jsmithers/deleteme/node_modules/@cucumber/language-service/src/tree-sitter-node/NodeParserAdapter.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Comment by aslakhellesoy** [comment]
What operating system are you on @jonsmithers?

**Comment by aslakhellesoy** [comment]
I know what the problem is. The language-service lib doesn’t declare `tree-sitter` as a dependency.

I think the easiest way to change this is to use the wasm bindings instead. I’ll create a fix for this.
